### ISSUE TITLE
"Device scrobbling disabled - incompatible iTunes plugin - please update"

### ISSUE THREAD

**Issue by saulshanabrook** [lastfm/lastfm-desktop#39]
I am getting a message saying "Device scrobbling disabled - incompatible iTunes plugin - please update".

However if I click on "please update", nothing happens.

Device scrobbling is indeed disabled.

I am running version 2.1.36 with iTunes 11.1 (but this message came up on previous iTunes versions as well) and Mac OS X 10.8.5.

**Comment by mamuf** [comment]
Same issue here with scrobbler version 2.1.37, iTunes 12.3.3.17, OS X 10.11.4 :-(

**Comment by Anahkiasen** [comment]
Same here, OSX 10.2.1, iTunes 12.5.3.17, scrobbler 2.1.37

**Comment by SunSparc** [comment]
Ditto.

**Comment by usbsnowcrash** [comment]
Same issue?!?

**Comment by josefson** [comment]
Same issue.

**Comment by ben-xo** [comment]
I'm sorry to say that "Device Scrobbling" (i.e. iPod scrobbling) isn't going to get fixed.

With modern iPods (and iPhones and iPads) you can scrobble on the device itself.

**Comment by Anahkiasen** [comment]
But only if you listen to music through the scrobbler app no?

**Comment by Anahkiasen** [comment]
Oh! I did *not* know that, the text on the download page just says it scrobbles but it mostly describes the app as a music player so I always assumed it required listening to music through it. Guess I don't need this bug fixed on my end then, nice.

**Comment by ben-xo** [comment]
The text on the download page for iOS probably needs updating, I will flag that up. Thanks for pointing it out.

**Comment by ennorehling** [comment]
@ben-xo I think this report is about the macOS desktop scrobbler, not iOS. Either that, or I'm watching the wrong ticket.

**Comment by joeyinbox** [comment]
Except that you have to manually open the app and tap the "Scan" button at least once every 2 months. 
This is not an automatic process anymore..

**Comment by Anahkiasen** [comment]
Hm that's true, maybe it's on the roadmap, hopefully.

**Comment by ben-xo** [comment]
@ennorehling this ticket IS about the Desktop scrobbler; my point was that for iOS devices, you no longer need the "Device Scrobbling" integration that the Desktop scrobbler once provided because there is now a good way to scrobble from the device.

Unfortunately that doesn't solve the problem for older iPods, but if you're attached to legacy hardware perhaps a legacy machine with an older iTunes will be the solution!

**Comment by ben-xo** [comment]
I would very much like it if we could automate scrobbling from the device, unfortunately Apple have made that very difficult for us…

**Comment by asbjornu** [comment]
Same problem here with Last.fm Scrobller version 2.1.37. Clicking the "please update" link does absolutely zip and zilch.

![screen shot 2018-03-05 at 22 17 51](https://user-images.githubusercontent.com/12283/37000244-1476ff5c-20c3-11e8-90cd-83fafb8be1fc.png)

**Comment by ssx** [comment]
Can confirm this is still occurring now.

**Comment by glyph** [comment]
It sounds like the resolution here should just be that it stops displaying this banner?

**Comment by ssx** [comment]
Yeah I’d say so, scrobbling still looks to be working fine.

**Comment by zippy72** [comment]
That device scrobbling has been removed makes me very sad. 99% of my scrobbling is still done with an iPod classic. I've just upgraded it with an iFlash so that isn't going to change for a good many years yet.

**Comment by theLMGN** [comment]
I'm in the same boat as zippy, attempting to manually scrobble just gives a long winded version of the error message
```
=========lastfm
[200402 15:36:38] unicorn::CoreApplication::init() Introducing "iPodScrobbler 2" 
[200402 15:36:38] unicorn::CoreApplication::init() Directed by Unknown 
[200402 15:36:38] unicorn::CoreApplication::init() Plugin DIR "/Applications/Last.fm.app/Contents/Helpers/../plugins" 
[200402 15:36:38] The iTunes pluggin is old and incompatible. Please update. Shutting down ("/Applications/Last.fm.app/Contents/MacOS/../Helpers/iPodScrobbler", "--device", "background", "--vid", "0000", "--pid", "0000", "--serial", "automatic") ```
