### ISSUE TITLE
Last.fm not scrobbling on W8.1

### ISSUE THREAD

**Issue by khaosdoctor** [lastfm/lastfm-desktop#56]
Last.fm scrobbler is not working on itunes, since it has updated its version I can't scrobble anything.

**Comment by hordecore** [comment]
+ 1.

Windows 8.1 and latest iTunes don't work.
On Mac OS X and latest iTunes everything is ok.
I found out some guy in support forum write out some alternative plugin that works and share it on github.

**Comment by Guts** [comment]
It's a hot topic on LastFM forums: http://www.lastfm.fr/forum/34905/_/2239688
And there is an alternative: http://www.lastfm.fr/forum/34905/_/2239688/52#f21149386

But since a few an update of LastFM scrobbler is available to fix it.
