### ISSUE TITLE
Failed to download resource "kde-phonon"

### ISSUE THREAD

**Issue by redCupWeeknd** [lastfm/lastfm-desktop#58]
After running `brew install phonon-vlc` I'm getting this error:  

    curl: (6) Could not resolve host: ftp.kde.org
    Error: Failed to download resource "kde-phonon"
    Download failed: ftp://ftp.kde.org/pub/kde/stable/phonon/4.6.0/src/phonon-4.6.0.tar.xz  

Does anyone know of a work around?

Thanks.

**Comment by joeyinbox** [comment]
The download url has changed to:
http://download.kde.org/stable/phonon/4.6.0/src/phonon-4.6.0.tar.xz

Type the following command:
``
brew edit kde-phonon
``

This will open the corresponding formula in your text editor.
Replace the content by this one for example: 
https://github.com/adymo/homebrew-kde/blob/master/kde-phonon.rb

Save and retry the command:
``
brew install qt kde-phonon
``

You should now be able to continue with the rest.
Cheers

**Comment by redCupWeeknd** [comment]
Great! That worked however, it looks like you have to replace the original checksum with the sha-256 version which is found on the actual [downloads](http://download.kde.org/stable/phonon/4.6.0/src/phonon-4.6.0.tar.xz.mirrorlist) page under file information:  

    SHA-256 Hash: 2915e7a37c92a0a8237b9e6d2ef67ba8b005ee3529d03991cd3d137f039ba3c4  

After replacing the URL and checksum its works fine.
