### ISSUE TITLE
libavcodec is deprecated

### ISSUE THREAD

**Issue by Soyasi** [lastfm/lastfm-desktop#62]
I´m trying to compile the program with opensuse 42.2, but can not since libavcodec is deprecated in its programming:

> compiling LAV_Source.cpp
> LAV_Source.cpp: In member function ‘uint8_t* LAV_SourcePrivate::decodeOneFrame(int&, int&, int&)’:
> LAV_Source.cpp:116:49: error: ‘avcodec_alloc_frame’ was not declared in this scope
>      AVFrame *decodedFrame = avcodec_alloc_frame();
>                                                  ^
> LAV_Source.cpp:292:37: error: ‘avcodec_free_frame’ was not declared in this scope
>      avcodec_free_frame(&decodedFrame);
>                                      ^
> LAV_Source.cpp: In member function ‘void LAV_Source::release()’:
> LAV_Source.cpp:409:62: error: ‘CODEC_ID_NONE’ was not declared in this scope
>      if ( d->inCodecContext && d->inCodecContext->codec_id != CODEC_ID_NONE )
>                                                               ^
> Makefile:252: recipe for target '_build/LAV_Source.o' failed
> make[1]: *** [_build/LAV_Source.o] Error 1
> make[1]: Leaving directory '/home/soyasi/Descargas/lastfm-desktop-master/app/fingerprinter'
> Makefile:224: recipe for target 'sub-app-fingerprinter-make_default-ordered' failed
> make: *** [sub-app-fingerprinter-make_default-ordered] Error 2

Is there any intention of putting this program up to date in linux?

**Comment by ben-xo** [comment]
Hi there,

The Last.fm Desktop app isn't much use on OpenSuse - it doesn't provide any functionality. libavcodec was only used for radio streaming, which Last.fm hasn't had for several years.

The remaining functions of the Last.fm Desktop app are for scrobbling from media players such as WinAmp or iTunes.
